version: '3'

services:
  breviori_db:
    container_name: breviori_db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  breviori_redis:
    container_name: breviori_redis
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  breviori: 
    image: breviori:latest
    container_name:  breviori
    ports:
      - "8000:8000"
    environment:
      - BREVIORI_REDIS_HOST=breviori_redis:6379
      - BREVIORI_REDIS_USERNAME=breviori
      - BREVIORI_REDIS_PASSWORD=breviori
      - BREVIORI_PG_HOST=breviori_db
      - BREVIORI_PG_PORT=5432
      - BREVIORI_PG_USER=postgres
      - BREVIORI_PG_PASSWORD=password
      - BREVIORI_PG_DATABASE=postgres
    depends_on:
      - breviori_db
      - breviori_redis